version: '3.7'

services:
  lft_dev:
    restart: always
    container_name: lft_dev
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
      - 9229:9229
    command: npm run start:debug
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    depends_on:
      - db

  db:
    restart: always
    container_name: db
    image: postgres:13.2
    env_file:
      - .docker.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    restart: always
    image: nginx:1.21.4
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  pgdata:
