name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [dev]

jobs:
  check_if_not_dependabot_pr:
    runs-on: ubuntu-20.04

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Check if PR is not a dependabot commit
        run: echo "All good. :)"

  unit-tests:
    runs-on: ubuntu-20.04

    needs: [check_if_not_dependabot_pr]

    steps:
      - uses: actions/checkout@v2

      - name: Install npm packages
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit
